### ISSUE TITLE
Promise pls?

### ISSUE THREAD

**Issue by chez14** [lpinca/freenom#1]
Is this project currently supporting Promise to handle such as callback?

Thanks!

**Comment by lpinca** [comment]
Hi,
no it only works with callbacks. Also Freenom API only worked with reseller accounts, I don't if it is still the case.

You can try to [`promisify`](http://bluebirdjs.com/docs/api/promise.promisify.html) the API but I'm not sure if it works.

**Comment by chez14** [comment]
uh, I see that's why I can't keep logging in :(
Is the reseller account registration's payment only counted as one-time payment? I mean, register once, use forever?

**Comment by lpinca** [comment]
@onlyongunz I don't know, you better ask Freenom support :)

**Comment by chez14** [comment]
okidoki, thanks
