### ISSUE TITLE
Error: Login credentials do not match any account

### ISSUE THREAD

**Issue by reteps** [lpinca/freenom#2]

**Comment by lpinca** [comment]
Freenom API only worked with reseller accounts, I don't know if it is still the case.

**Comment by reteps** [comment]
i mean, i got my version to work.

**Comment by sooluh** [comment]
Looks like we got fooled by api documentation from freenom. probably api v2 is not fully developed yet. I tried with v1 and it worked. I made a pull request for it, please review @lpinca.

#cmiiw
Thank you in advance.

**Comment by lpinca** [comment]
v1 or v2 does not make any difference for me

```
$ curl -X GET "https://api.freenom.com/v2/domain/search?domainname=test001.tk&email=myemail&password=mypassword&domaintype=PAID"
{
  "error": "Login credentials do not match any account",
  "status": "error"
}
```

```
curl -X GET "https://api.freenom.com/v2/domain/search?domainname=test001.tk&email=myemail&password=mypassword&domaintype=PAID"
{"error":"Login credentials do not match any account","status":"error"}
```

**Comment by sooluh** [comment]
Sorry, the curl commands you attached are all using v2. I've tried using mocha with v1 and it works fine. Everything passed!

**Comment by lpinca** [comment]
Tests also pass with v2. Tests are run with https://github.com/nock/nock. They do not hit the real endpoints.

**Comment by sooluh** [comment]
ok, my bad. but strange, earlier I tried to use v2 there was an error then I tried v1 and it was safe, everything worked. while I just tried again, what happens is all errors. I will close my pull request. thank you :smile:

**Comment by riotoff** [comment]
I just want to change the dns records of the domain, but I get an error, please help me solve the problem

**Comment by testbot-github** [comment]
> I just want to change the dns records of the domain, but I get an error, please help me solve the problem

same here

**Comment by sebastian-kay** [comment]
![image](https://user-images.githubusercontent.com/5553159/193075181-4d2de693-cf41-4560-a2ec-cc9805c824fe.png)


> I just want to change the dns records of the domain, but I get an error, please help me solve the 
> problem

And the same problem here via web interface.

**error:** "Login credentials do not match any account",
**status:** "error"

**Comment by Origincookie122** [comment]
Trying to change DNS Records 
getting error login credentials do not match

**Comment by Moaht** [comment]
I'm also getting this same issue when trying to change DNS Records. 
Hoping/supposing this is just due to some sort of server maintenance/downtime/load? And will resolve itself?

**Comment by lpinca** [comment]
See https://github.com/lpinca/freenom/issues/2#issuecomment-358353709.

**Comment by THEGAMER20081** [comment]
also having the same issue don't have a reseller account and im using just the normal site
